branches:
  except:
    - gh-pages
image: Visual Studio 2017
init:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME" }
      else { Update-AppveyorBuild -Version "dev-$($Env:APPVEYOR_REPO_COMMIT.Substring(0, 7))" }
environment:
  SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder
  PRIV_KEY:
    secure: DP0MMmNx8N5NEY+E50itzl6w7JX08ARMWjzGPwZtKeiKZtQ3tfF/I3w462A4xhArvSokODxdIAGxEjNTrGu5phJ6b2KH7bcH5baG0RXHg42OErC2btph9iTrefCsa+vZTn0NgTUudlegX5sw6DnLHQ3x5uq8DM0KJ9Xbkbz7jbQW7IeHCLddXAEyqHpKhn693KADHbyL6mXU7VnlZhPtMaawISYMM3ZO9EllRWXddW6B3cGeG+gUx1yuZbU7eX/5cVaxeL/elEJQF0H/Gq1OLjD/WLG6mfo3llqEeXc2uyvGc7f3q+Qv8QdgTwjlgpN4aar1q80xQXXM7gdsCCPm4XjnJl5j7+18tJ9dULVEHILiVQcoidfe6yQPaQ5k++wBpongIwtZIwaas5dIhkBGdJSfQspoXM7BsrFWX/c2msNeZKuu9EupX45l58u0pZyY6/6+gp53i/fumgqlC1ORxQ==
install:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true")
      {
          $keyFile = "C:\Users\appveyor\.ssh\id_ed25519"
          sc "$keyFile" "-----BEGIN OPENSSH PRIVATE KEY-----`n" -NoNewLine
          ac "$keyFile" $Env:PRIV_KEY.Replace(" ", "`n") -NoNewLine
          ac "$keyFile" "`n-----END OPENSSH PRIVATE KEY-----`n" -NoNewLine
          git config --global user.name "$Env:APPVEYOR_REPO_COMMIT_AUTHOR"
          git config --global user.email "$Env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL"
      }
  - ps: |
      Invoke-WebRequest -Uri https://github.com/EWSoftware/SHFB/releases/download/v2017.1.28.0/SHFBInstaller_v20171.28.0.zip -OutFile SHFBInstaller.zip
      7z e "SHFBInstaller.zip" "InstallResources\SandcastleHelpFileBuilder.msi"
      rm "SHFBInstaller.zip"
      start -Wait msiexec "/i `"SandcastleHelpFileBuilder.msi`" /quiet /qn /norestart"
  - ps: |
      Invoke-WebRequest -Uri "https://dotnet.myget.org/F/nuget-build/api/v2/package/NuGet.CommandLine" -OutFile "NuGet.nupkg"
      7z e "NuGet.nupkg" "tools\NuGet.exe"
      rm "NuGet.nupkg"
configuration: Release
build:
  project: BaiduPanApi.sln
  parallel: true
before_build:
  - ps: .\NuGet restore
after_build:
  - ps: |
      git clone -b gh-pages https://github.com/$Env:APPVEYOR_REPO_NAME gh-pages
      cd gh-pages
      if (Test-Path "docs") { rm -r "docs" }
      mv "..\docs"
      git add -A
      git clean -dfx
      cp -r "docs" ".."
      if ($Env:APPVEYOR_REPO_TAG -eq "true")
      {
          git remote set-url origin git@github.com:$Env:APPVEYOR_REPO_NAME
          git commit -m "Documentation updated for $Env:APPVEYOR_REPO_TAG_NAME."
          git push
      }
      cd ..
  - ps: |
      $config = $Env:CONFIGURATION
      $project = $Env:APPVEYOR_PROJECT_NAME
      $name = "BaiduPanApi-$Env:APPVEYOR_BUILD_VERSION"
      $dir = "bin\$config"
      if ($Env:APPVEYOR_REPO_TAG -eq "true") { .\NuGet pack -Properties Configuration=$config -Symbols }
      md "$name"
      cp @("$dir\*.dll", "$dir\$project.xml", "$dir\$project.pdb", "LICENSE") "$name"
      7z a "$name.zip" "$name"
      ren "docs" "$name-docs"
      7z a "$name-docs.zip" "$name-docs"
artifacts:
  - path: '*.nupkg'
  - path: '*.zip'
deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    prerelease: true
    description: |
      **Release Notes**
      - Some exception stack trace information is now preserved.
      - This release is mainly for testing the new keys after switching to a new account.
    auth_token:
      secure: saJApLHQjPJ+XmMy3Qk+khAvfIKI4dveBtSnUESRX14qpUy3WPlhM97Ixbja/Tjg
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: 36z2xiUQ/AJY8ftiUBVRF2eA902THRRfWmlxDtmo9srIGw5FiI/vHyn71WUYc0YX
    on:
      appveyor_repo_tag: true
