image: Visual Studio 2017 RC
init:
  - ps: |
      if ($Env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME" }
      else { Update-AppveyorBuild -Version "dev-$($Env:APPVEYOR_REPO_COMMIT.Substring(0, 7))" }
install:
  - ps: |
      Invoke-WebRequest -Uri "https://dotnet.myget.org/F/nuget-build/api/v2/package/NuGet.CommandLine" -OutFile "NuGet.nupkg"
      7z e "NuGet.nupkg" "tools\NuGet.exe"
      rm NuGet.nupkg
configuration: Release
build:
  project: BaiduPanApi.sln
  parallel: true
before_build:
  - ps: .\NuGet restore
after_build:
  - ps: if ($Env:APPVEYOR_REPO_TAG -eq "true") { .\NuGet pack -Prop Configuration=Release }
  - ps: |
      $name = "BaiduPanApi-$Env:APPVEYOR_BUILD_VERSION"
      md "$name"
      cp "bin\$Env:CONFIGURATION\*.dll" "$name"
      7z a "$name.zip" "$name"
artifacts:
  - path: '*.nupkg'
  - path: '*.zip'

deploy:
  - provider: GitHub
    artifact: /.*\.zip/
    prerelease: true
    description: |
      **Release Notes**
      - Migrate to use `System.Net.Http.HttpClient` as the underlying HTTP library.
      - Almost all public methods are changed to use `async` and added an `Async` suffix.
      - Add support for copying.
      - Cookies checking on login is removed.
      - Cache is now disposed in `CachedBaiduPanContent.Dispose()`.
      - Corresponding cache entries will be cleared after uploading files in `CachedBaiduPanContent`.
      - `DeleteItemAsync()`, `MoveItemAsync()` and `RenameItemAsync()` now return correct error codes.
      - The `IsUnknownError` property of `BaiduPanApiException` and `BaiduPanLoginException` now returns correct value.
    auth_token:
      secure: 5AlQWeRE8ygXF64hrS4Eix9lMiicAnetjiu9l91QHTb2Oao+gBnPHsIGdEh5GCvM
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: ns4FQHCpiRJ4EfFSKpIMEHYX8H+kUVg7xsZWLXbI2yg17TLkjGPd/LrLQf3ZHD0B
    on:
      appveyor_repo_tag: true
